services:
  api:
    container_name: api
    build:
      context: .
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: setphx_dev
      DB_PORT: 5432
      DB_HOST: database
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/deps
      - /app/_build

  database:
    container_name: database
    image: postgres:13.6-alpine
    ports:
       - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/docker-initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

volumes:
  pgdata:

